### ISSUE TITLE
[Feature Request] Add Australian METAR source

### ISSUE THREAD

**Issue by thommo17** [ScottSturdivant/rpi_metar#10]
Hi,

I thought I would just start a thread on this to make it more "official".

As per my previous comment on the other issue I have been looking for a reliable source for METARs to add.

I have come across some code that might help figure things out here

http://hackage.haskell.org/package/metar

It uses the Australian Bureau of Meteorology website 

http://www.bom.gov.au/aviation/forecasts/taf/

Does this seem like a realistic addition to the project?

I'll keep looking for some other sources too

**Comment by ScottSturdivant** [comment]
Yes, that looks like it would work just fine.  Thank you for finding this!  I'll hopefully be able to add it in the next week or so.

Thank you again!

**Comment by thommo17** [comment]
Awesome!

I look forward to the update and thank you for doing all of this. It really is great work and I really appreciate it

**Comment by peepsnet** [comment]
https://github.com/ScottSturdivant/rpi_metar/blob/211e0e9240c65f0f3ed6f9bfeb9a876c30a673a2/rpi_metar/scripts/init.py#L47-49

Im not sure where this file is called from or when it is used but it does check for a K in the beginning of the entry and adds a K then checks against the NOAA metar API. 

This will have to be changed as to not add a K but to reject the 3 CHAR ID as a hole and ask only for a 4 CHAR ID and then use the First or First and Second letter to determine which source API to check against!

K = US sources

Y = AU sources

EG = United Kingdon

https://en.wikipedia.org/wiki/ICAO_airport_code#Prefixes

A little digging and I found this:

https://apidocs.checkwx.com/

You can try local METAR retrieval then as a last resort use checkwx.com

Great can-o-worms. Should be fun!

:)

**Comment by thommo17** [comment]
Oh that does look like a good source. Just too bad that it has a 2000 a day request limit which would be reached in about 40 mins for AU.

I don't know if it would really matter if it adds a K to any 3 letter code as all ICAO codes are 4 letters anyway so it would only be an issue if a code had a typo and left out a letter. Correct?

**Comment by thommo17** [comment]
I also noticed something just now with the difference between US METARs and AU is that visibility is in statute miles but in Aus it is in meters. I tried to have a look at the code to see if this would be a problem when it is manually parsing the text but I just don't really have the coding knowledge to see what is really happening.

If a METAR was to look like this METAR YORG 050430Z AUTO 16007 7000 // BKN028 09/02 Q1026 RMK would that show as blue since 7000m is 4.34SM?

**Comment by ScottSturdivant** [comment]
Wow, that checkwx site looks great! The rate limits seem really restrictive though. 

Re: the init script - that's just something I use to help initially program a map. As you've seen, if you insert all 4 chars of the ICAO it'll take it as is. But as I'm US based, and lazy, well...that's why it accepts a three digit shortcut and assumes the geography!  (For some of my maps on the borders, I can use 3 chars for the US, then switch to 4 when appropriate, e.g. CYYZ.)  Anyhow, we could add a --geo switch or something along those lines so rather than assuming 'K', it could be overridden on the command line.

Disclaimer: I am not a pilot.  So in AU, how is the visibility defined in the METAR string?  Is it always the 5th field, or...?  For the US it was 'easy' since I could just look for "SM" and it was the numbers preceding it.  Are the flight category rules the same in AU in that 7000m should be MVFR?  And BKN028 would be a ceiling at 2800m or 9186ft?

**Comment by thommo17** [comment]
Here's a good guide for METARs in Australia

http://www.bom.gov.au/aviation/data/education/metar-speci.pdf

It is pretty much always the same field but some can say cavok if it is a clear day as it says in the pdf. 

They are a little different as shown here

https://www.avplan-efb.com/tips/at-a-glance-metars/

But I was planning on forking the code eventually and changing it myself so not make it difficult for you as I could imagine it would confuse things. Also it's not really that big of a deal

**Comment by thommo17** [comment]
This site has all the METARs also if you wanted to have a browse to see what they look like.

http://www.bom.gov.au/aviation/observations/metar-speci/

Maybe if there was a catch-all that if it sees cavok then it just makes it vfr but if no cavok then it does the full text parse?

**Comment by thommo17** [comment]
Something was bugging me about the differences between the US and AU flight categories so I went back and looked at that link from earlier (https://www.avplan-efb.com/tips/at-a-glance-metars/) and realised that they all equal the same but just one is in SM and the other meters.

Maybe all it will take is a little maths in the code to say if vis is 4 digits divide by 1609.34 to get miles and then continue on as normal after that?

Dunno why I got them all confused but maybe now it won't be too big of a deal

**Comment by thommo17** [comment]
Hi Scott,

Have you had any progress on the AU METARs at all?

**Comment by ScottSturdivant** [comment]
No progress yet, my apologies.  I'll be sure to update this when I have had the chance to tackle it!

**Comment by thommo17** [comment]
Completey understand mate :)

I'm just happy you're even willing to give it a go for me

**Comment by thommo17** [comment]
Well I have finally had a crack at getting the BOM source to work and I have come up with this.


```
import requests
import re

URL =  'http://www.bom.gov.au/aviation/php/process.php'

payload = {
        'keyword': input('Input ICAO code: '),
        'type': 'search',
        'page': 'TAF'
}

r = requests.post(URL, data=payload)

match = re.search(r'(?P<METAR>(METAR|SPECI).*?)<br />', r.text)

if match:
    metar_info = match.group('METAR')
    try:
        print(metar_info)
    except AttributeError:
        metar_info = None
```


Obviously it is super basic but it works.

Just needs to be made into a class and have all the other bells and whistles added to it like the other ones which you.

Codes that aren't Australian give an attribute error so I weeded them out as well.

Does this help at all?

**Comment by ScottSturdivant** [comment]
@thommo17 This BOM source is now in develop.  Thank you again for your help!
