### ISSUE TITLE
Change Ceiling regex to include SCT and Visibility regex to include metric

### ISSUE THREAD

**Issue by thommo17** [ScottSturdivant/rpi_metar#12]
Hi @ScottSturdivant,

I've been looking into the way wx.py parses the METARs and thought these changes may help get a bit more colour on the maps.

I would do a pull request but still don't really know how github works all that well.

on line 38 I think SCT should be added to pick up cloud that defines 3-4  octas which means 3-4 out of 8 parts of sky covered with cloud. 

    match = re.search(r'(VV|SCT|BKN|OVC)(?P<ceiling>\d{3})', metar_info)

FEW could also be added but in my experience METARs that show FEW generally have very little cloud in the area and it only defines 1-2 octas. It is still technically a ceiling though.

Also, in the effort to help with the metric units for visibility I believe this regex would work well in conjuction with the code you already have.

    match = re.search(r'\s(?P<visibility>\d{4}|\/{4})\s', metar_info)
    if match:
        visibility = match.group('visibility')
        try:
            visibility = float(visibility) / 1609
        except ZeroDivisionError:
            visibility = None
        except ValueError:
            visibility = None

All metric METARs use 4 digits (or //// for no vis data) surrounded by whitespace for visibility.

The ValueError will pick up the //// as none since it is a METAR with no data for vis

Not sure how you'd integrate it though. Just thought I'd try to make your life easier when you try  to do it. I'm sure there is a quick way to join them that I just haven't learnt yet.

Thanks, Matt

**Comment by ScottSturdivant** [comment]
Hi Matt!

Thanks for your patience, been out of town for a while.  Starting to look at this.  The[ FAA defines](http://www.faraim.org/faa/far/14CFR/vol1/part1/index.html) the ceiling as: 

>  "the height above the earth's surface of the lowest layer or clouds or obscuring phenomena that is reported as "broken", "overcast", or "obscuration", and not classified as "thin" or "partial".

Therefore I do not believe that SCT or FEW should be added to the ceiling regex.

Thanks for the pointers for the visibility regex.  By any chance have you given any thought to the way the sources are instantiated?  https://github.com/ScottSturdivant/rpi_metar/blob/develop/rpi_metar/core.py#L53

Ideally it'd be nice if AU users could use the AU source first, falling back to aviationweather.gov as secondary, etc.

**Comment by thommo17** [comment]
Hi Scott,

Yeah that's fair. I did a little research myself into the definition and found [this ICAO definition](http://essentialpilot.co.za/2017/10/15/cloud-base-vs-ceiling/)

> Ceiling – According to the ICAO legal definition, ceiling is the height above the ground or water of the base of the lowest layer of cloud below 20 000ft covering more than half the sky. Simply put, ceiling is referred to when the clouds start to hold hands and form layers i.e. the amount of cloud is defined as either broken (BKN 5-7 Octas) or overcast (OVC 8 Octas).

So I agree with you. It does raise another complication though if you want to follow it perfectly and that is if there is 2 cloud layers reported they actually add onto each other's cloud cover octas.

So an example would be FEW010 and SCT020 would actually be 1-2 octas plus 3-4 octas which is 4-6 octas taking it over the half of the sky covered metric. Now I know that would be a bitch to code so I'll leave it to you if you want to even try that.

As for the sources I just assumed it would be one of the sources down the list as the other ones work fine at the moment and as I'm still learning python the code is going over my head on how it all works right now.

I guess you could put something in there to catch all Y codes and send them to the BOM source first but I don't think it is necessary. I'd say it would be fine to grab the NOAA source for the 98 that it covers and then the rest will fail over to the BOM.

If you're trying to future proof it and keep resources to a minimum maybe separating the airports by ICAO code prefix letter wouldn't be too bad. A Y code could go to BOM first and all the European codes could go to their respective "best" source etc stopping it from even trying the NOAA but NOAA does a really good job of collecting METARs from all over the world anyway. Just not all of the little airports.

Also, if I'm reading the Skyvector source code correctly it would require the AU airports to have their coordinates added to the us-airports.csv file as well to work. Is that right?

PS for testing the BOM source with AU airports NOAA doesn't have you could use YARM.

**Comment by ScottSturdivant** [comment]
@thommo17 I believe this can be closed now that the AU BOM source is present, along with the ability to cycle through the various data sources.  Thank you so much for your assistance!
