### ISSUE TITLE
Allow duplicate LEDs not working

### ISSUE THREAD

**Issue by thommo17** [ScottSturdivant/rpi_metar#21]
HI Scott,

I've come across an issue where I can't have 2 LEDs use the same airport code. It'll give this error

I realised that the code is meant to accept duplicates after reading the config readme and felt like an idiot so now I've edited this issue to reflect the new problem.

```
Feb 25 12:39:09 Australian-METAR-Map rpi_metar[13392]: 2021-02-25 12:39:09,738 - rpi_metar.airports - ERROR - 0.4 - metar_processor - YMAV1 has no data.
                                                       Traceback (most recent call last):
                                                         File "/opt/rpi_metar_au/lib/python3.7/site-packages/rpi_metar/airports.py", line 79, in process_metar
                                                           metar = metars[self.code]
                                                       KeyError: 'YMAV1'
Feb 25 12:39:09 Australian-METAR-Map rpi_metar[13392]: 2021-02-25 12:39:09,740 - rpi_metar.core - INFO - 0.4 - render_leds - got YBLT
Feb 25 12:39:09 Australian-METAR-Map rpi_metar[13392]: 2021-02-25 12:39:09,746 - rpi_metar.airports - ERROR - 0.4 - metar_processor - YMAV2 has no data.
                                                       Traceback (most recent call last):
                                                         File "/opt/rpi_metar_au/lib/python3.7/site-packages/rpi_metar/airports.py", line 79, in process_metar
                                                           metar = metars[self.code]
                                                       KeyError: 'YMAV2'

```

Will the code need to clip the number off the end of the airport code at some point to allow the sources to find it?

Thanks

**Comment by ScottSturdivant** [comment]
Hey Matt,

This functionality was added here: https://github.com/ScottSturdivant/rpi_metar/commit/93daefb4a63ba0d44a477b8f4b02f3f279a54171

At least, I think that does what you're after!  So, do:

YMAV1 = 27
YMAV2 = 28

Let me know how you get on!

**Comment by thommo17** [comment]
> Hey Matt,
> 
> This functionality was added here: [93daefb](https://github.com/ScottSturdivant/rpi_metar/commit/93daefb4a63ba0d44a477b8f4b02f3f279a54171)
> 
> At least, I think that does what you're after! So, do:
> 
> YMAV1 = 27
> YMAV2 = 28
> 
> Let me know how you get on!

Yeah I feel dumb because I read that and had to go change the whole topic.

Doing that doesn't work still.

```
Feb 25 12:39:09 Australian-METAR-Map rpi_metar[13392]: 2021-02-25 12:39:09,738 - rpi_metar.airports - ERROR - 0.4 - metar_processor - YMAV1 has no data.
                                                       Traceback (most recent call last):
                                                         File "/opt/rpi_metar_au/lib/python3.7/site-packages/rpi_metar/airports.py", line 79, in process_metar
                                                           metar = metars[self.code]
                                                       KeyError: 'YMAV1'
Feb 25 12:39:09 Australian-METAR-Map rpi_metar[13392]: 2021-02-25 12:39:09,740 - rpi_metar.core - INFO - 0.4 - render_leds - got YBLT
Feb 25 12:39:09 Australian-METAR-Map rpi_metar[13392]: 2021-02-25 12:39:09,746 - rpi_metar.airports - ERROR - 0.4 - metar_processor - YMAV2 has no data.
                                                       Traceback (most recent call last):
                                                         File "/opt/rpi_metar_au/lib/python3.7/site-packages/rpi_metar/airports.py", line 79, in process_metar
                                                           metar = metars[self.code]
                                                       KeyError: 'YMAV2'
```


any ideas?

**Comment by thommo17** [comment]
Actually just leave it with me for a bit because I think I need to make that change on my own fork.

I'll let you know.

Sorry. Feeling a bit scattered now haha

**Comment by ScottSturdivant** [comment]
No problem!

Check the referenced commit (https://github.com/ScottSturdivant/rpi_metar/commit/93daefb4a63ba0d44a477b8f4b02f3f279a54171) for the other changes to the files. From your traceback, it doesn't look like you've got them in place:

https://github.com/ScottSturdivant/rpi_metar/blob/develop/rpi_metar/airports.py#L80

Yours is showing metars[self.code], where it should be metars[self.code[:4]]

**Comment by thommo17** [comment]
And there we go all fixed!

You're the best. Thanks for being so quick to respond too! Better than a lot of other IT support desks out there

Cheers

Matt
