### ISSUE TITLE
upgrade rpi-ws281x

### ISSUE THREAD

**Issue by resteinbock** [ScottSturdivant/rpi_metar#3]
Mind bumping the version for rpi-ws281x? Looks like I am getting an error for unsupported hardware running a 3 B+.

I don't know much about python or whether [changing this line](https://github.com/ScottSturdivant/rpi_metar/blob/663e8e6f80b87063230bdee489490bf86035723b/requirements.txt#L3) would fix things -- sorry for not submitting a PR.

After the change is made, how would I get the changes to my Pi?

<img width="1231" alt="screen shot 2019-01-01 at 8 37 15 pm" src="https://user-images.githubusercontent.com/6557722/50579032-e967d700-0e06-11e9-920a-87022d37af76.png">
<img width="1258" alt="screen shot 2019-01-01 at 8 46 47 pm" src="https://user-images.githubusercontent.com/6557722/50579033-eb319a80-0e06-11e9-845a-d0a2079c7828.png">

**Comment by ScottSturdivant** [comment]
Sure thing! I'm not around my hardware at the moment so I cannot do a real release (as I'd like to verify nothing breaks before releasing), but I've pushed a change and you can install from git and give it a shot.

You'll probably first need to install git on your pi:  `apt install git -y`  (All commands assume you've logged in as root.)

Next, whack the current `rpi_metar` install.

`systemctl stop rpi_metar && rm -rf /opt/rpi_metar && python3 -m venv /opt/rpi_metar && source /opt/rpi_metar/bin/activate`

Finally, clone from git and install the latest develop branch:

```source /opt/rpi_metar/bin/activate
git clone https://github.com/ScottSturdivant/rpi_metar.git
cd rpi_metar
pip install -e .
systemctl start rpi_metar
```

**Comment by resteinbock** [comment]
Thanks for the quick response Scott! I won't have a chance to get back to this either until next week. I'll let you know how it goes.
