### ISSUE TITLE
METAR_REFRESH_RATE is defined incorrectly

### ISSUE THREAD

**Issue by peepsnet** [ScottSturdivant/rpi_metar#8]
METAR_REFRESH_RATE is defined as an integer that reflects the time the system will wait before refetching metar info. This values is said to be in minutes as per your readme.md

However the value is then used several places in a sleep function:
```python
time.sleep(cfg.getint('settings', 'metar_refresh_rate', fallback=METAR_REFRESH_RATE))
```
https://github.com/ScottSturdivant/rpi_metar/blob/a7a8394a42afd3264d880a9dcd1b71cebb5db690/rpi_metar/core.py#L83

And wait function:
```python
event.wait(cfg.getint('settings', 'metar_refresh_rate', fallback=METAR_REFRESH_RATE))
```
https://github.com/ScottSturdivant/rpi_metar/blob/a7a8394a42afd3264d880a9dcd1b71cebb5db690/rpi_metar/core.py#L215

Here it is clearly in seconds

https://github.com/ScottSturdivant/rpi_metar/blob/a7a8394a42afd3264d880a9dcd1b71cebb5db690/rpi_metar/core.py#L23

Currently:

| Option             | Default | Description                                                     |
|--------------------|---------|-----------------------------------------------------------------|
| metar_refresh_rate | 5       | An integer that controls how frequently (in minutes) the METAR information is polled. 

Just change the README.md to:

| Option             | Default | Description                                                     |
|--------------------|---------|-----------------------------------------------------------------|
| metar_refresh_rate | 300     | An integer that controls how frequently (in seconds) the METAR information is polled.

**Comment by peepsnet** [comment]
| Option             | Default | Description                                                     |
|--------------------|---------|-----------------------------------------------------------------|
| metar_refresh_rate | 5       | An integer that controls how frequently (in minutes) the METAR information is polled.

**Comment by peepsnet** [comment]
Here it is clearly in seconds

https://github.com/ScottSturdivant/rpi_metar/blob/a7a8394a42afd3264d880a9dcd1b71cebb5db690/rpi_metar/core.py#L23

**Comment by ScottSturdivant** [comment]
Thanks for pointing this out!  I'll be updating the README shortly.

**Comment by peepsnet** [comment]
easiest way to fix it! LOL
